### ISSUE TITLE
Problems with logical description of joints

### ISSUE THREAD

**Issue by jasperkoid** [sigproc/robotic_surgery#22]
![joint2](https://cloud.githubusercontent.com/assets/7999696/5472590/27b1f7b4-85fa-11e4-8d28-d01e1393c34f.png)
![joint3](https://cloud.githubusercontent.com/assets/7999696/5472591/28c29b2c-85fa-11e4-84ca-3aa619cf7064.png)
The robot looks fine on RViz when you run it, but problems arise when I incorporate it with the setup assistant of MoveIt!, probably due to some underlying error of joint description.

**Comment by Somahtr** [comment]
Not sure if this issue has already been resolved, but if not the changes introduced in PR #23 may provide a solution.

**Comment by jasperkoid** [comment]
Thanks for the help - the collision states are straightforward to fix. For future reference, note that you need to manually disable the collision between the right_gripper_link with wrist_roll_link. 

My main problem is actually with the chain descriptions of the links - I'm concerned that it may cause a problem later on, and is especially important for path planning/inverse kinematics. After further investigation with the latest description file, I realised:

![right_gripper](https://cloud.githubusercontent.com/assets/7999696/5614034/63f5345e-94e4-11e4-8125-73171ad8f290.png)
Is it possible to group the right gripper, right connector, right finger link etc. into a single claw group? At the moment, it seems possible to vary each individually which cause disfiguration of the arm:

![separate_gripper](https://cloud.githubusercontent.com/assets/7999696/5614036/67376524-94e4-11e4-998b-e72b303dcd72.png)

**Comment by Somahtr** [comment]
This issue has been fixed in PR #24
